version: '3'
services:
  proxy:
    build: proxy/.
    ports:
      - "80"
      - "443"
    links:
      - "chilate:chilate"
      - "compras:compras"
  dns:
    build: dns/.
    ports:
      - "53"
    depends_on:
      - proxy
    links:
      - "proxy:proxy"
  chilate:
    build: chilate/.
    ports:
      - "80"
  compras:
    build: compras/.
    ports:
      - "443"
